### ISSUE TITLE
Deployment phase - notification 'ships cant fit the board' 

### ISSUE THREAD

**Issue by emperorjun** [pielegacy/battleship#5]
this notification was said even though all the ships are shown in the UI to be properly deployed

**Comment by emperorjun** [comment]
There is probably something wrong with the array[] mapping of the game during deployment

**Comment by KC-T1** [comment]
I think it's not entirely a bug.
That notification displayed when u want to put the ship inappropriately, for example when u tried to deploy aircraft carrier at the edge of grid.
I think it's more like an enchantment that can be added so that either the notification can faded away after certain amount of time (more probable) or we display a log for notification.

**Comment by KC-T1** [comment]
It's done.
Please tell me if the delay is too much or not
